apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: readfile-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: readfile-container
    spec:
      volumes:
      - name: test-storage
        persistentVolumeClaim:
         claimName: test-claim
      containers:
      - name: readfile-container
        image: balram2496/readfile
        volumeMounts:
        - mountPath: /readwrite
          name: test-storage
